version: "3.3"

services:
  app:
    build:
      context: ./app
    restart: always
    ports:
      - 3000:3000

  server:
    build:
      context: ./server
    restart: always
    ports:
      - 8080:8080
